### PR TITLE
Id3 jumper

### PR DESCRIPTION
**Pull request by TheNitek**
Rebased PR #23 and did some minor tweaks (jump ID3 tags when playing file and simplified isMP3File() )

### CODE REVIEW

**Comment by ladyada** [comment]
thanks, what boards did you test this on?

**Comment by TheNitek** [comment]
just to also document it here:  @leftCoast tested this on teensy in #23 

I just tested it successfully on Arduino Uno.

**Comment by ladyada** [comment]
squahsed and merged!

**Comment by leftCoast** [comment]
Cool! Now we can move on!

**Comment by TheNitek** [comment]
Thank you for all your great work @ladyada! And thanks again @leftCoast for this great improvement!

Would it maybe be possible to do a new release of this lib?

**Comment by ladyada** [comment]
yep!
@szymonkaliski wanna practice doing a release? :)

**Comment by szymonkaliski** [comment]
@ladyada -> https://github.com/adafruit/Adafruit_VS1053_Library/pull/51 :)

**Comment by ladyada** [comment]
@szymonkaliski ahh sorry added the team as writable, please commit direct and release - then delete the PR :)

**Pull request merged**
