### PR TITLE
#18 Make record_ogg example record while button is pressed

### PR DESCRIPTION
**Pull request by TheNitek**
Make the record_ogg example record while the button is pressed until it is released

### CODE REVIEW

**Comment by ladyada** [comment]
hiya have you tested this?

**Comment by TheNitek** [comment]
No, unfortunately I don't have the right setup at hand, but from looking at the code it seems quite obvious that it would stop recording if you keep the button pressed for to long, so recording for as long as the button is pressed looks like an easy solution.

**Comment by ladyada** [comment]
hiya, you'd be surprised what causes something to not work :) we'll hold off on this until someone can test it with hardware! thank you!

**Comment by akumbara** [comment]
Hi, I tested this and it works.

**Comment by TheNitek** [comment]
Can this be merged then?

**Comment by yo2ldk** [comment]
until the end, we can do it record on SD card with vs1053 or not?

**Pull request merged**
