### PR TITLE
allowed playing a file in endless loop

### PR DESCRIPTION
**Pull request by Krakenus**
I added a possibility to play a file in and endless loop until the playback is stopped by `stopPlaying` method.
I tested it using Arduino Uno and Arduino Uno Wifi R2 with this shield. https://www.elecrow.com/vs1053-mp3-shield-p-777.html

### CODE REVIEW

**Review by MarcHagen — APPROVED** [review]
LGTM & Tested

**Comment by johnwargo** [comment]
@ladyada can you have someone look at these pull requests? Many of them are years old.

**Comment by ladyada** [comment]
@johnwargo hiya some of these need some work/testing before they can be merged, is that something you can help with?

**Comment by johnwargo** [comment]
I can sure try, although I'm not an expert in C, especially low level stuff. I have a bevvy of Adafruit Feather boards here, the sound board, and a crapload of experience with Arduino (https://johnwargo.com/categories/arduino/ and https://johnwargo.io/iot) - but you'd have to let me know what you want done. 

Some of the PRs are years old, someone should respond at a minimum to those and identify what needs to happen next so the community can jump in an help.

Look at this one, it's approved, right? Or do you need multiple approvals?

**Comment by johnwargo** [comment]
I'll make the change this evening and test it. Any reason not to make it `playbackLooping(bool en)` or just `playbackLoop(bool en)`  to keep it simple? It's a little weird to pass a `false` to `enableLooping` to turn it off (from a readability standpoint).

**Comment by ladyada** [comment]
tbh we don't care much what the function is called, as long as it takes in an argument rather than having two funcitons :)

**Comment by johnwargo** [comment]
@ladyada please close this as my PR from last week implements this.

**Pull request closed without merging**
