### PR TITLE
Fix pausePlaying when currentTrack has ended (Fix #16)

### LINKED ISSUE #16: pausePlaying function has issue with else statement causing issue with stopped
The pausePlaying function has an issue where the else statement would set playingMusic to true despite the currentTrack has finished if you call pausePlaying with false.
This causes the call to the function stopped to return false despite the fact that the currentTrack has
stopped because playingMusic was flipped to true despite that not being true.

This is my fix. I tried to commit to the git but I don't have the permissions:

void Adafruit_VS1053_FilePlayer::pausePlaying(boolean pause) {
if (pause) 
playingMusic = false;
else {
// Added this because
// calling pausePlaying with false would
// caused the call to stopped to return
// false despite the fact that the track
// has indeed stopped playing.
// Could add else{ playingMusic = false; }
// but it seems unnecessary.
if (currentTrack)
{
playingMusic = true;
}
feedBuffer();
}
}

### PR DESCRIPTION
**Pull request by TheNitek**
Fixes issue #16 as suggested there to prevent playingMusic to become true when currentTrack is already finished.

### CODE REVIEW

**Comment by jamesguan** [comment]
Is this still being maintained? I brought up that issue #16 a while back and I see this is still an issue. While I can fork the library, I feel that the fix would help the broader community. Especially because the sound will stop playing after a while.

**Comment by ladyada** [comment]
hiya - this PR is not easily mergable because of updates & changes we've done since. if someone can re-apply/test/submit we'll take a look. the toughest part of taking PRs is that a large # of PRs we get break functionality and are not tested w/a variety of hardware. that's why they are not instantly merged.

**Comment by jamesguan** [comment]
@ladyada I understand. I currently need this for a current intent. I will open a PR and contribute. Thank you!

**Comment by TheNitek** [comment]
I guess I'm closing this one then ...

**Pull request closed without merging**
