### PR TITLE
Add fast forward feature to playing sound tracks.

### PR DESCRIPTION
**Pull request by cogliano**
This pull request adds the ability to speed-up or fast forward tracks using the built-in feature of the VS1053 chip. Two functions were added:

- setPlaySpeed(uint16_t speed) - set the play speed. Speed is defined by an integer, i.e. 1 is normal playback, 2 is 2x playback, 3 is 3x playback, etc.
- getPlaySpeed() - get the current play speed

I have been using it in my own code for a while and thought it would be useful to contribute it to the library.

To test, simply add a statement like "musicPlayer.setPlaySpeed(2);" to the player_simple.ino example prior to the musicPlayer.startPlayingFile() call.

### CODE REVIEW

**Review by jacgoudsmit — CHANGES_REQUESTED** [review]
There is a bug in getPlaySpeed: the function returns before turning the interrupts back on.

**Comment by cogliano** [comment]
Just fixed it. Thanks, I should have seen that.

**Comment by MaxPleaner** [comment]
Thank you for sharing this @cogliano, was trying to figure this out

**Comment by MaxPleaner** [comment]
I wonder how difficult it would be to add the ability to slow down, or to manipulate the audio in a more fluid way (e.g. control the speed with a slider).

**Comment by MaxPleaner** [comment]
I actually just figured this out. If anyone else is curious, you can change the play speed fluidly using sample rate:

```
void Adafruit_VS1053_FilePlayer::setSampleRate(uint16_t sampleRate) {
  noInterrupts();
  sciWrite(VS1053_REG_AUDATA, sampleRate);
  interrupts();
}
```

Need to call this _after_ `startPlayingFile` which sets the initial sample rate.
You can  then run

```
 uint16_t track_info = musicPlayer.sciRead(VS1053_REG_AUDATA);  //SCI_AUDATA
 int rate = (track_info >> 1) * 2;
 int stereo = ((track_info << 15) >> 15);
```

To read the auto-calculated sample rate, before adjusting it to your liking,.

Awesome!!

**Comment by ladyada** [comment]
this one looks OK - thanks for reviewing1

**Pull request merged**
