### PR TITLE
Fix pausePlaying function to not make playingMusic true if there is n…

### LINKED ISSUE #16: pausePlaying function has issue with else statement causing issue with stopped
The pausePlaying function has an issue where the else statement would set playingMusic to true despite the currentTrack has finished if you call pausePlaying with false.
This causes the call to the function stopped to return false despite the fact that the currentTrack has
stopped because playingMusic was flipped to true despite that not being true.

This is my fix. I tried to commit to the git but I don't have the permissions:

void Adafruit_VS1053_FilePlayer::pausePlaying(boolean pause) {
if (pause) 
playingMusic = false;
else {
// Added this because
// calling pausePlaying with false would
// caused the call to stopped to return
// false despite the fact that the track
// has indeed stopped playing.
// Could add else{ playingMusic = false; }
// but it seems unnecessary.
if (currentTrack)
{
playingMusic = true;
}
feedBuffer();
}
}

### PR DESCRIPTION
**Pull request by jamesguan**
Resolves #16 

Thank you for creating a pull request to contribute to Adafruit's GitHub code!
Before you open the request please review the following guidelines and tips to
help it be more easily integrated:

- **Describe the scope of your change--i.e. what the change does and what parts
  of the code were modified.**  This will help us understand any risks of integrating
  the code.

Fixed the `void Adafruit_VS1053_FilePlayer::pausePlaying(boolean pause)` function to accurately set `playingMusic` bool true only when there is a current track. This will prevent the scenario where `stopped` function will return false while the current track has indeed stopped.

Also, this prevents crashes that might occur when the library tries to play a track that has been closed.

- **Describe any known limitations with your change.**  For example if the change
  doesn't apply to a supported platform of the library please mention it.

- **Please run any tests or examples that can exercise your modified code.**  We
  strive to not break users of the code and running tests/examples helps with this
  process.
Tested functions locally on system.

To duplicate the issue, play a sound file and wait till it is stopped. Call the `pausePlaying` function and then call the `stopped` function, you should incorrectly get `false` for the status. 

Thank you again for contributing!  We will try to test and integrate the change
as soon as we can, but be aware we have many GitHub repositories to manage and
can't immediately respond to every request.  There is no need to bump or check in
on a pull request (it will clutter the discussion of the request).

Also don't be worried if the request is closed or not integrated--sometimes the
priorities of Adafruit's GitHub code (education, ease of use) might not match the
priorities of the pull request.  Don't fret, the open source community thrives on
forks and GitHub makes it easy to keep your changes in a forked repo.

After reviewing the guidelines above you can delete this text from the pull request.

### CODE REVIEW

**Comment by jamesguan** [comment]
Review Ready

**Comment by jamesguan** [comment]
Is there anything extra I need to do to get this PR merged?

**Comment by jacgoudsmit** [comment]
> Is there anything extra I need to do to get this PR merged?

Just be patient I guess.

Adafruit has a LOT of repositories on Github so it may take some time before they get to this one. Also I understand they're mostly focusing on CircuitPython right now.

In the meantime, your PR is visible and can be pulled by others who find it useful.

**Comment by ladyada** [comment]
hiya if other people can test the PRs that is helpful, we have 1200 repos and many PRs :)

**Comment by TheNitek** [comment]
I also just stumbled upon this bug and can confirm this fix works.

**Comment by TheNitek** [comment]
Any chance to get this merged soon? Anything I can do to help?

**Comment by TheNitek** [comment]
Awesome, thx!

**Comment by jamesguan** [comment]
Yay!

**Pull request merged**
